### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by mocode808** [PlanTeam/BSON#6]
Will this work with Xcode 7.3.1* which uses Swift 2.2.1?

The snapshot version makes xCode crash for me so I'm going to be using the stable release rather than the snapshot.
Not sure if this will cause issues.

**Comment by Obbut** [comment]
We currently only support the Swift 3.0 development snapshot from 2016-04-12 and have no intentions to support a stable Swift version until Swift 3 comes out later this year.

We just got used to the Xcode crashes 😁

**Comment by Joannis** [comment]
Okay. We need to discuss this properly @Obbut .

@mocode808 Feel free to join us on the slack shown in the README.

**Comment by Joannis** [comment]
We're supporting BSON for Swift 2.2 later today

**Comment by mocode808** [comment]
By supporting BSON for Swift 2.2 do you mean that using the Xcode version 7.3.1 will work with MongoKitten then? Thanks guys I appreciate the help.

I'd really like to use this project in my project for uploading video files but I can't seem to get the SPM to work at all :(

**Comment by Joannis** [comment]
@mocode808 MongoKitten 0.9.0 should work with swift 2.2 for 100%.
Part of this process was porting BSON to swift 2.2 which is the newly released 2.3.0 version of BSON

**Comment by Joannis** [comment]
@mocode808 Feel free to join our slack for any questions regarding MongoKitten, CryptoKitten and BSON. Any feedback is appreciated!
